import { ProductReportData } from './pdfService';

export class FallbackPDFService {
  static generateSimplePDF(productData: ProductReportData): Buffer {
    // Generate a simple text-based PDF content
    const content = `
PRODUCT TRANSPARENCY REPORT
==========================

Product Name: ${productData.name}
Category: ${productData.category}
Generated: ${new Date().toLocaleString()}

DETAILED ASSESSMENT
==================

${productData.answers.map((answer, index) => `
${index + 1}. ${this.formatQuestionId(answer.questionId)}
   Answer: ${this.formatAnswer(answer.answer)}
`).join('\n')}

---
This report was automatically generated by the Altibbe Product Transparency System
    `;

    // For now, return a simple text buffer
    // In a real implementation, you might use a lighter PDF library like jsPDF
    return Buffer.from(content, 'utf-8');
  }

  private static formatQuestionId(questionId: string): string {
    return questionId
      .replace(/_/g, ' ')
      .replace(/\b\w/g, l => l.toUpperCase());
  }

  private static formatAnswer(answer: any): string {
    if (typeof answer === 'boolean') {
      return answer ? 'Yes' : 'No';
    }
    if (typeof answer === 'object') {
      return JSON.stringify(answer, null, 2);
    }
    return String(answer);
  }
}
